ports:
  - port: 3000
    visibility: public
    
tasks:
  - name: allocation-ui
    before: pnpm -v || curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
    init: pnpm i
    command: pnpm dev --force
    openMode: split-right
    
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true

vscode:
  extensions:
    - steoates.autoimport
    - coenraads.bracket-pair-colorizer-2
    - pustelto.bracketeer
    - mhutchie.git-graph
    - eamodio.gitlens
    - dsznajder.es7-react-js-snippets
    - voorjaar.windicss-intellisense
    - dbaeumer.vscode-eslint
